# Python_data
Data Analysis

UTF-8 Encoding 과정에서 오류
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

encoding = 'CP949' 로 불러온다
